---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: phpapp
  name: nginx-configmap
data:
  nginx.conf: |
    server {
        server_name _;
        root /var/www;
        index index.php index.html index.htm;
        location ~ \.php$ {
            # 404
            try_files                     $fastcgi_script_name =404;
            # default fastcgi_params
            include                       /etc/nginx/fastcgi_params;
            # fastcgi settings
            fastcgi_pass                  127.0.0.1:9000;
            fastcgi_index                 index.php;
            fastcgi_buffers               8 16k;
            fastcgi_buffer_size           32k;
            # fastcgi params
            fastcgi_param DOCUMENT_ROOT   $document_root;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTP_PROXY '';
        }
        location / {
            try_files $uri $uri/ /index.php?q=$uri&$args =404;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-http-service
  namespace: phpapp
spec:
  selector:
    app: phpapp
  ports:
    - port: 80
      targetPort: 80
      name: nginx-http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-http-ingress
  namespace: phpapp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: info.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-http-service
                port:
                  name: nginx-http
